services:
  # web:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db
  db:
    image: postgres
    environment:
      - .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

