POST http://[::1]:3000/customer
Content-Type: application/json

{
  "firstName": "Joeyddf",  
  "lastName": "Milledff",
  "email": "joe-m24@gmail.com",
  "phone": "0700000000",
  "streetAddress": "Barrio San Pedro Street 310 y Av.",
  "city": "Los Angeles",
  "postCode": "90001",
  "dateOfBirth": "2020-01-01",
  "country": "California, USA"
}
