POST http://[::1]:3000/room-type
Content-Type: application/json


{
  "name": "Deluxe Room",
  "description": "A spacious room with a king-size bed and a beautiful view.",
  "pricePerNight": 150.00,
  "maxGuests": 2
}
