POST http://[::1]:3000/hotel
Content-Type: application/json

{
  "name": "Hotel California",
  "description": "Hotel 66 California",
  "street_address": "424 E Palm Canyon Dr, Palm Springs, CA 92264",
  "state": "California, USA",
  "city": "Malibu",
  "country": "United State of America",
  "phone": "0142458790",
  "email": "hotel-california.com"
}
